### PR TITLE
Update the repo structure to handle multiple project

### PR DESCRIPTION
**Pull request by Francois-Werbrouck**
ref #68

### CODE REVIEW

**Comment by Francois-Werbrouck** [comment]
Hi @sylvanie85 and @k-allagbe, I've refactor the structure of the Datastore and updated the documentation. Let me know what you think of it.

**Comment by Francois-Werbrouck** [comment]
We also need to update the Backend of Nachet because I've removed the default value given to parameters in few functions.

**Comment by Francois-Werbrouck** [comment]
I have updated the Pyproject, however, I'm quite unsure about how they work.

**Comment by k-allagbe** [comment]
> I have updated the Pyproject, however, I'm quite unsure about how they work.

I'm not either. Checkout the structure in https://github.com/ai-cfia/azure-db where each folder (package) has it's own `setup.py`. And for the installation in the `finesse-backend/requirements.txt`, I used:

```
git+https://github.com/ai-cfia/azure-db.git@main#subdirectory=azure-ai-search
```

This would work okay. If we want to version each package individually though, I don't know any way other than separate them in their own repo.

Please @ai-cfia/devops, give your opinions.

**Review by sylvanie85 — COMMENTED** [review]
LGTM
I'll create an issue on backend to update it, let me know when you think it's done I'll be able to test if everything is still working before your merge 

Edit :
https://github.com/ai-cfia/nachet-backend/issues/107

**Review by sylvanie85 — APPROVED** [review]
LGTM, everything is working on nachet (just need to merge https://github.com/ai-cfia/nachet-backend/issues/107)
well done! 🤠

**Comment by Francois-Werbrouck** [comment]
image
as shown, all tests are passing. However, the workflow needs to be updated I think to search only for 'test_*.py'

**Pull request merged**
